### ISSUE TITLE
The target_gear field is not working

### ISSUE THREAD

**Issue by jason890088** [lgsvl/LGSVLControlSensor#3]
I am trying to use the ros2 command to control the vehicle with LGSVLControlSensor, I can successfully move it forward with the following ros2 command, but when I trying to change gear the target_gear field does not work.

```bash
ros2 topic pub --once /lgsvl/vehicle_control_cmd lgsvl_msgs/msg/VehicleControlData "
{
header: {stamp: {sec: 0, nanosec: 0}, frame_id: ""},
acceleration_pct: 1.0,
braking_pct: 0.0,
target_wheel_angle: 0.0,
target_wheel_angular_rate: 0.0,
target_gear: 0
}
"
```

**Comment by EricBoiseLGSVL** [comment]
We have added this functionality in the next release.  Thanks for posting

**Comment by jason890088** [comment]
Thanks for your reply.
